name: foundation-ts
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pytorch
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - jupyterlab
  - pip
  - pip:
      - hydra-core
      - omegaconf

