name: foundation-ts
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pytorch
  - numpy=1.25.2
  - pandas=2.1.4
  - scikit-learn
  - matplotlib
  - jupyterlab
  - pip
  - pip:
      - hydra-core
      - omegaconf
      - momentfm
